
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config
install:
  - pip install -r requirements.txt
script:
  - pytest
notifications:
  email: false