os: windows
language: sh
before_install:
- choco install python3 --params "/InstallDir:C:\\Python"
- export PATH="/c/Python:/c/Python/Scripts:$PATH"
- python -m pip install --upgrade pip wheel
install:
  - pip install -r requirements.txt
script:
  - pytest
notifications:
  email: false