
language: python
python:
  - "3.6"
  - "3.7"
variables:
    QT_QPA_PLATFORM: "offscreen"
before_install:
  - sudo apt-get update
  - sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config
install:
  - pip install -r requirements.txt
script:
  - pytest -s
notifications:
  email: false