
language: python
cache: pip
jobs:
  include:
      - name: "Python 3.8-dev on Linux"
        python: "3.8-dev"
        install:
          - sudo apt-get update
          - sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config libdbus-1-3 libxkbcommon-x11-0
        services:
          - xvfb
      - name: "Python 3.8 on Linux"
        python: "3.8"
        install:
          - sudo apt-get update
          - sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config libdbus-1-3 libxkbcommon-x11-0
        services:
          - xvfb
      - name: "Python 3.7 on Linux"
        python: "3.7"
        install:
          - sudo apt-get update
          - sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config libdbus-1-3 libxkbcommon-x11-0
        services:
          - xvfb
      - name: "Python 3.6 on Linux"
        python: "3.6"
        install:
          - sudo apt-get update
          - sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config libdbus-1-3 libxkbcommon-x11-0
        services:
          - xvfb
      - name: "Python 3.5 on Linux"
        python: "3.5"
        install:
          - sudo apt-get update
          - sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config libdbus-1-3 libxkbcommon-x11-0
        services:
          - xvfb
      - os: osx
        osx_image: xcode11.3
        language: shell
        install:
          - brew install leptonica
          - brew install tesseract
        env:
          - PYTHON=3.8.1
          - PYTHON=3.7.6
          - PYTHON=3.6.10
          - PYTHON=3.5.9
before_install:
  - pip3 install -r requirements.txt
env:
  - QT_QPA_PLATFORM="offscreen"
script:
  - pytest -s
notifications:
  email: false