
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
variables:
    QT_QPA_PLATFORM: "offscreen"
before_install:
  - sudo apt-get update
  - sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config libdbus-1-3 libxkbcommon-x11-0
services:
  - xvfb
install:
  - pip install -r requirements.txt
script:
  - pytest -s
notifications:
  email: false